plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mitmachim.applocker'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mitmachim.applocker'
        minSdk 19
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
